from .models import Word

# parts of speech constants
POS_ADJECTIVE = "adj."
POS_ADVERB = "adv."
POS_NOUN = "n."
POS_VERB = "v."

words = [
    Word(
        word="accordion",
        part_of_speech=POS_NOUN,
        definitions=[
            "A small, portable, keyed wind instrument, whose tones are generated by play of the wind upon free metallic reeds.",
        ],
    ),
    Word(
        word="aground",
        part_of_speech=POS_ADVERB,
        definitions=[
            "On the ground; stranded; -- a nautical term applied to a ship when its bottom lodges on the ground.",
        ],
    ),
    Word(
        word="tacit",
        part_of_speech=POS_ADJECTIVE,
        definitions=[
            "Silently indicated or implied; understood from conditions or circumstances; inferred or inferable; expressed otherwise than by speech; indirectly manifested or communicated; wordless.",
            "*logic* Not derived from formal principles of reasoning; based on induction rather than deduction.",
        ],
    ),
    Word(
        word="epee",
        part_of_speech=POS_NOUN,
        definitions=[
            "*fencing* A fencing sword of a certain modern type; frequently opposed to foil and sabre.",
        ],
    ),
    Word(
        word="letup",
        part_of_speech=POS_NOUN,
        definitions=[
            "A reduction in pace, force, or intensity; a slowdown.",
        ],
    ),
    Word(
        word="lollop",
        part_of_speech=POS_VERB,
        definitions=[
            "To walk with a bouncing motion.",
        ],
    ),
    Word(
        word="lope",
        part_of_speech=POS_VERB,
        definitions=[
            "To run or ride with a steady, easy gait.",
        ],
    ),
    Word(
        word="loupe",
        part_of_speech=POS_NOUN,
        definitions=[
            "A magnifying glass, usually mounted in an eyepiece, often used by jewellers and watchmakers.",
        ],
    ),
    Word(
        word="opulent",
        part_of_speech=POS_ADJECTIVE,
        definitions=[
            "Characterized by extravagance or rich abundance; lavish or luxuriant.",
        ],
    ),
    Word(
        word="outpoll",
        part_of_speech=POS_VERB,
        definitions=[
            "To win more votes than.",
        ],
    ),
    Word(
        word="peloton",
        part_of_speech=POS_NOUN,
        definitions=[
            "*cycling* The main group of riders formed during a cycling road race.",
        ],
    ),
    Word(
        word="penult",
        part_of_speech=POS_NOUN,
        definitions=[
            "The next-to-last syllable of a word.",
            "The next to the last in a series.",
        ],
    ),
    Word(
        word="pone",
        part_of_speech=POS_NOUN,
        definitions=[
            "*southern* US A baked or fried cornbread (bread made of cornmeal), often made without milk or eggs.",
        ],
    ),
    Word(
        word="poppet",
        part_of_speech=POS_NOUN,
        definitions=[
            "*informal* An endearingly sweet or beautiful child.",
            "*informal* A young woman or girl.",
            "A figurine or image of idolatry.",
            "A doll made in witchcraft to represent a person, used in casting spells on that person.",
        ],
    ),
    Word(
        word="poult",
        part_of_speech=POS_NOUN,
        definitions=[
            "A young table-bird: turkey, partridge, grouse etc.",
        ],
    ),
    Word(
        word="pule",
        part_of_speech=POS_VERB,
        definitions=[
            "To whine; whimper.",
        ],
    ),
    Word(
        word="pullet",
        part_of_speech=POS_NOUN,
        definitions=[
            "A young hen, especially one less than a year old.",
            "*slang* A spineless person; a coward.",
        ],
    ),
    Word(
        word="pullout",
        part_of_speech=POS_NOUN,
        definitions=[
            "A withdrawal, especially of armed forces",
            "An object, such as a newspaper supplement that can be pulled out from something else",
        ],
    ),
    Word(
        word="putout",
        part_of_speech=POS_NOUN,
        definitions=[
            "A play made by one or more fielders that causes a batter or a base runner to be ruled out.",
        ],
    ),
    Word(
        word="tope",
        part_of_speech=POS_NOUN,
        definitions=[
            "*noun* A small shark (Galeorhinus galeus) that has a long pointed snout and is commercially harvested for food and oil.",
            "*verb* *archaic* To drink excessively; to get drunk.",
        ],
    ),
    Word(
        word="tuneup",
        part_of_speech=POS_NOUN,
        definitions=[
            "An adjustment made to an engine in order to improve its performance",
        ],
    ),
    Word(
        word="tupelo",
        part_of_speech=POS_NOUN,
        definitions=[
            "Any of several trees of the genus Nyssa of Asia and the eastern United States, having simple alternate leaves and small flowers.",
        ],
    ),
]
