name: Spelling Bee Answers

on:
  # # for debugging
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: 0 8 * * *  # daily at 8 am UTC (== 3 am eastern) [the new game starts daily at 3 am eastern]
concurrency: ci-spelling-bee-answers

jobs:

  answers:
    name: Answers
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      # repo_root: $GITHUB_WORKSPACE  # todo: update settings code to support expanding env vars
      repo_root: /home/runner/work/spelling-bee-answers/spelling-bee-answers

    steps:

      - name: Git checkout
        uses: actions/checkout@v3.3.0

      - name: Poetry setup
        uses: gr1n/setup-poetry@v8
        with:
          poetry-version: 1.3.2

      - name: Python setup
        id: python-setup
        uses: actions/setup-python@v4.5.0
        with:
          python-version-file: .python-version
          cache: poetry

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          poetry install

      - name: Run scraper
        timeout-minutes: 2
        env:
          display_puzzle_output: true
        run: |
          poetry run python -m spelling_bee_answers.scrapers.nyt

      - name: Git commit answers
        uses: endbug/add-and-commit@v9.1.1
        with:
          cwd: days
          add: .
          author_name: ${{ vars.ROBOT_AUTHOR_NAME }}
          author_email: ${{ vars.ROBOT_AUTHOR_EMAIL }}
          message: Add answers

      - name: Update readme table
        timeout-minutes: 1
        env:
          display_generated_readme_table: false
        run: |
          poetry run python -m spelling_bee_answers.days

      - name: Git commit readme
        uses: endbug/add-and-commit@v9.1.1
        with:
          add: README.md
          author_name: ${{ vars.ROBOT_AUTHOR_NAME }}
          author_email: ${{ vars.ROBOT_AUTHOR_EMAIL }}
          message: Regenerate readme table

      - name: Update stats
        timeout-minutes: 1
        run: |
          poetry run python -m spelling_bee_answers.stats

      - name: Git commit word lists
        uses: endbug/add-and-commit@v9.1.1
        with:
          add: Pangrams.md Words.md
          author_name: ${{ vars.ROBOT_AUTHOR_NAME }}
          author_email: ${{ vars.ROBOT_AUTHOR_EMAIL }}
          message: Regenerate word lists
