name: Spelling Bee Answers

on:
  # for debugging 2
  push:
    branches:
      - main
  schedule:
    - cron: 0 8 * * *  # daily at 8 am UTC (== 3 am EST) [the new daily game starts at 3 am EST]
concurrency: ci-spelling-bee-answers

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.3.0

      - name: Poetry setup
        uses: gr1n/setup-poetry@v8
        with:
          poetry-version: 1.3.2

      - name: Python setup
        id: python-setup
        uses: actions/setup-python@v4.5.0
        with:
          python-version-file: .python-version
          cache: poetry

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          poetry install

      - name: Run scraper
        timeout-minutes: 2
        env:
          display_puzzle_output: true
        run: |
          poetry run python app.py

      - name: Git commit answers
        uses: endbug/add-and-commit@v9.1.1
        with:
          cwd: days
          add: .
          author_name: Robot
          author_email: ci@taylore.dev
          message: Add answers

      - name: Update readme table
        timeout-minutes: 1
        env:
          display_generated_readme_table: false
        run: |
          poetry run python gen_readme_table.py

      - name: Git commit readme
        uses: endbug/add-and-commit@v9.1.1
        with:
          add: README.md
          author_name: Robot
          author_email: ci@taylore.dev
          message: Regenerate readme table
